apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wateen
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ahmadshen/argocd'
    path: frontend/  # This should be a relative path
    targetRevision: HEAD
    helm:
      valueFiles:
      - frontend/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
